(linenum) @tag
(comment_text) @comment

(integer) @number
(string) @string
(int_scalar) @variable
(int_array) @variable
(str_scalar) @variable
(str_array) @variable
(str_slice) @variable

(rem_tok) @comment
(plus_tok) @operator
(minus_tok) @operator
(times_tok) @operator
(div_tok) @operator
(mod_tok) @operator
(pow_tok) @operator
(gtr_tok) @operator
(eq_tok) @operator
(less_tok) @operator
(and_tok) @operator
(or_tok) @operator
(not_tok) @operator
(n_tok) @operator

(at_tok) @keyword.builtin
(call_tok) @keyword.builtin
(coloreq_tok) @keyword.builtin
(dim_tok) @keyword.builtin
(dsp_tok) @keyword.builtin
(end_tok) @keyword.builtin
(for_tok) @keyword.builtin
(gosub_tok) @keyword.builtin
(goto_tok) @keyword.builtin
(gr_tok) @keyword.builtin
(hlin_tok) @keyword.builtin
(if_tok) @keyword.builtin
(inn_tok) @keyword.builtin
(input_tok) @keyword.builtin
(list_tok) @keyword.builtin
(next_tok) @keyword.builtin
(nodsp_tok) @keyword.builtin
(notrace_tok) @keyword.builtin
(plot_tok) @keyword.builtin
(poke_tok) @keyword.builtin
(pop_tok) @keyword.builtin
(prn_tok) @keyword.builtin
(print_tok) @keyword.builtin
(rem_tok) @keyword.builtin
(return_tok) @keyword.builtin
(step_tok) @keyword.builtin
(tab_tok) @keyword.builtin
(text_tok) @keyword.builtin
(then_tok) @keyword.builtin
(to_tok) @keyword.builtin
(trace_tok) @keyword.builtin
(vlin_tok) @keyword.builtin
(vtab_tok) @keyword.builtin

(sgnp_tok) @function.builtin
(absp_tok) @function.builtin
(scrnp_tok) @function.builtin
(pdlp_tok) @function.builtin
(rndp_tok) @function.builtin
(peekp_tok) @function.builtin
(lenp_tok) @function.builtin
(ascp_tok) @function.builtin
